Repository octokit/auth-oauth-user.js, pull requests merged in 2023-06, with the labels that each got.

#161 fix(build): switch to esbuild
  package-lock.json
  package.json
  scripts/build.mjs
  src/auth.ts
  src/hook.ts
  src/index.ts
  test/tsconfig.test.json
  tsconfig.json
Labels: Type: Maintenance

#155 ci: stop testing against NodeJS v14, v16
  .github/workflows/test.yml
  package-lock.json
  package.json
Labels: Type: Maintenance, Type: Breaking change

#167 docs: replace references to Skypack CDN with esm.sh
  README.md
Labels: Type: Documentation

#169 fix(build): explicitly mark type import
  src/get-authentication.ts
Labels: Type: Bug, Priority: High
