Repository octokit/auth-oauth-user.js, pull requests merged in 2024-02, with the labels that each got.

#241 maint: fix spelling errors
  CONTRIBUTING.md
  src/types.ts
  test/octokit.test.ts
Labels: Type: Maintenance

#244 feat: package is not ESM
  README.md
  package-lock.json
  package.json
  src/auth.ts
  src/get-authentication.ts
  src/hook.ts
  src/index.ts
  test/octokit.test.ts
  test/smoke.test.ts
  test/standalone.test.ts
  test/tsconfig.test.json
Labels: Type: Feature, Type: Breaking change

#245 fix(build): correctly output ESM
  scripts/build.mjs
Labels: Type: Bug

#247 fix(pkg): add `main` entry point
  scripts/build.mjs
Labels: Type: Bug
